package nl.t64.game.rpg.components.conversation


enum class ConversationCommand {
    EXIT_CONVERSATION,
    HERO_JOIN,
    HERO_DISMISS,
    LOAD_SHOP,
    SAVE_GAME,
    KNOW_QUEST,
    TOLERATE_QUEST,
    ACCEPT_QUEST,
    RECEIVE_ITEM,
    RECEIVE_XP,
    CHECK_IF_LINKED_QUEST_KNOWN,
    CHECK_IF_QUEST_ACCEPTED,
    CHECK_IF_IN_INVENTORY,
    COMPLETE_QUEST_TASK,
    RETURN_QUEST,
    ACCEPT_OR_RETURN_QUEST,
    REWARD_QUEST,
    BONUS_REWARD_QUEST,
    FAIL_QUEST,
    START_BATTLE,
    NONE
}
